language: node_js
node_js:
  - 12
install:
  - npm install -g codecov
  - npm ci
jobs:
  include:
    - stage: Unit test
      script: 
        - npm run coverage
        - codecov
    - stage: Release
      script: npm run build
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN
        local_dir: build
        keep_history: true
        on:
          branch: master
