const vanillaComponents = [
  [
    'LEATHER_SCRAPS',
    'https://vignette.wikia.nocookie.net/witcher/images/d/d7/Tw3_leather_scraps.png/revision/latest?cb=20170216074341',
    [
      [
        'LEATHER_STRAPS',
        "",
        4
      ]
    ]
  ],
  [
    'INFUSED_SHARD',
    'https://vignette.wikia.nocookie.net/witcher/images/f/fc/Tw3_infused_shard.png/revision/latest?cb=20170216074340',
    [
      [
        'INFUSED_DUST',
        "",
        2
      ]
    ]
  ],
  [
    'IRON_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/4/43/Tw3_iron_ingot.png/revision/latest?cb=20161028060254',
    [
      [
        'IRON_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'HARDENED_TIMBER',
    'https://vignette.wikia.nocookie.net/witcher/images/4/42/Tw3_hardened_timber.png/revision/latest?cb=20160920124252',
    [
      [
        'TIMBER',
        "",
        2
      ],
      [
        'RESIN',
        "",
        1
      ]
    ]
  ],
  [
    'INFUSED_DUST',
    'https://vignette.wikia.nocookie.net/witcher/images/b/b5/Tw3_infused_dust.png/revision/latest?cb=20160514072604',
    [
      [
        'POWDERED_MONSTER_TISSUE',
        "",
        1
      ],
      [
        'MONSTER_ESSENCE',
        "",
        1
      ]
    ]
  ],
  [
    'INFUSED_CRYSTAL',
    'https://vignette.wikia.nocookie.net/witcher/images/2/2e/Tw3_infused_crystal.png/revision/latest?cb=20170216074340',
    [
      [
        'INFUSED_SHARD',
        "",
        2
      ]
    ]
  ],
  [
    'GLOWING_ORE_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/5/52/Tw3_glowing_ore_ingot.png/revision/latest?cb=20170216074302',
    [
      [
        'GLOWING_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'HARDENED_LEATHER',
    'https://vignette.wikia.nocookie.net/witcher/images/f/fd/Tw3_hardened_leather.png/revision/latest?cb=20170216074340',
    [
      [
        'CURED_LEATHER',
        "",
        1
      ],
      [
        'WAX',
        "",
        4
      ]
    ]
  ],
  [
    'DARK_IRON_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/c/cf/Tw3_dark_iron_ingot.png/revision/latest?cb=20170216064638',
    [
      [
        'DARK_IRON_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'CURED_LEATHER',
    'https://vignette.wikia.nocookie.net/witcher/images/e/e2/Tw3_cured_leather.png/revision/latest?cb=20170216074257',
    [
      [
        'LEATHER_SCRAPS',
        "",
        4
      ]
    ]
  ],
  [
    'CURED_DRACONID_LEATHER',
    'https://vignette.wikia.nocookie.net/witcher/images/d/dc/Tw3_cured_draconid_leather.png/revision/latest?cb=20160705062241',
    [
      [
        'HARDENED_LEATHER',
        "",
        2
      ],
      [
        'CHITINOUS_SHELL',
        "",
        5
      ]
    ]
  ],
  [
    'DIMERITIUM_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/a/a8/Tw3_dimeritium_ingot.png',
    [
      [
        'DIMERITIUM_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'DIMERITIUM_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/a/a8/Tw3_dimeritium_ingot.png',
    [
      [
        'DIMERITIUM_ORE',
        "",
        1
      ],
      [
        'GLOWING_ORE_INGOT',
        "",
        1
      ]
    ]
  ],
  [
    'DARK_STEEL_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/1/1d/Tw3_dark_steel_ingot.png/revision/latest?cb=20160410152415',
    [
      [
        'DARK_IRON_INGOT',
        "",
        1
      ],
      [
        'STEEL_INGOT',
        "",
        1
      ]
    ]
  ],
  [
    'DARK_STEEL_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/1/1d/Tw3_dark_steel_ingot.png/revision/latest?cb=20160410152415',
    [
      [
        'DARK_IRON_ORE',
        "",
        2
      ],
      [
        'STEEL_INGOT',
        "",
        1
      ]
    ]
  ],
  [
    'DARK_STEEL_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/6/67/Tw3_dark_steel_plate.png/revision/latest?cb=20160305093625',
    [
      [
        'DARK_STEEL_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'DIMERITIUM_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/c/c4/Tw3_dimeritium_plate.png/revision/latest?cb=20160823085520',
    [
      [
        'DIMERITIUM_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'DIMERITIUM_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/7/76/Tw3_dimeritium_ore.png/revision/latest?cb=20170216064641',
    [
      [
        'DARK_STEEL_INGOT',
        "",
        1
      ],
      [
        'METEORITE_SILVER_INGOT',
        "",
        1
      ],
    ]
  ],
  [
    'METEORITE_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/1/1b/Tw3_meteorite_ingot.png/revision/latest?cb=20170216062819',
    [
      [
        'METEORITE_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'LINEN',
    'https://vignette.wikia.nocookie.net/witcher/images/0/0d/Tw3_linen.png/revision/latest?cb=20170216062819',
    [
      [
        'THREAD',
        "",
        4
      ]
    ]
  ],
  [
    'LESSER_GLYPH_OF_INFUSION',
    'https://vignette.wikia.nocookie.net/witcher/images/6/6b/Tw3_glyph_infusion_lesser.png/revision/latest?cb=20160418194405',
    [
      [
        'SILK',
        "",
        1
      ],
      [
        'POWDERED_PEARL',
        "",
        1
      ],
      [
        'FEATHER',
        "",
        1
      ],
      [
        'MONSTER_BLOOD',
        "",
        1
      ],
    ]
  ],
  [
    'LESSER_RUNESTONE',
    'https://vignette.wikia.nocookie.net/witcher/images/3/3b/Tw3_runestone_lesser.png/revision/latest?cb=20160319170925',
    [
      [
        'BLACK_PEARL_DUST',
        "",
        1
      ],
      [
        'INFUSED_DUST',
        "",
        1
      ]
    ]
  ],
  [
    'METEORITE_SILVER_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/5/5c/Tw3_meteorite_silver_ingot.png/revision/latest?cb=20170216062818',
    [
      [
        'METEORITE_SILVER_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'METEORITE_SILVER_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/5/5c/Tw3_meteorite_silver_ingot.png/revision/latest?cb=20170216062818',
    [
      [
        'METEORITE_INGOT',
        "",
        1
      ],
      [
        'SILVER_INGOT',
        "",
        1
      ],
    ]
  ],
  [
    'SILVER_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/8/80/Tw3_silver_ingot.png/revision/latest?cb=20160410120044',
    [
      [
        'SILVER',
        "",
        10
      ]
    ]
  ],
  [
    'SILVER_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/8/80/Tw3_silver_ingot.png/revision/latest?cb=20160410120044',
    [
      [
        'SILVER_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'SILK',
    'https://vignette.wikia.nocookie.net/witcher/images/a/a3/Tw3_silk.png/revision/latest?cb=20160323071607',
    [
      [
        'LINEN',
        "",
        2
      ]
    ]
  ],
  [
    'RESIN',
    'https://vignette.wikia.nocookie.net/witcher/images/d/d5/Tw3_resin.png/revision/latest?cb=20170216070818',
    [
      [
        'SAP',
        "",
        2
      ]
    ]
  ],
  [
    'STRING',
    'https://vignette.wikia.nocookie.net/witcher/images/c/cc/Tw3_string.png/revision/latest?cb=20160329073626',
    [
      [
        'THREAD',
        "",
        2
      ]
    ]
  ],
  [
    'STEEL_PLATES',
    'https://vignette.wikia.nocookie.net/witcher/images/3/31/Tw3_steel_plates.png/revision/latest?cb=20170216074401',
    [
      [
        'STEEL_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'STEEL_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/0/0f/Tw3_steel_ingot.png/revision/latest?cb=20160410151354',
    [
      [
        'IRON_INGOT',
        "",
        1
      ],
      [
        'COAL',
        "",
        1
      ]
    ]
  ],
  [
    'STEEL_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/0/0f/Tw3_steel_ingot.png/revision/latest?cb=20160410151354',
    [
      [
        'IRON_ORE',
        "",
        2
      ],
      [
        'COAL',
        "",
        1
      ]
    ]
  ],
  [
    'SILVER_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/f/f2/Tw3_silver_ore.png/revision/latest?cb=20160410115533',
    [
      [
        'SILVER',
        "",
        5
      ]
    ]
  ],
  [
    'SILVER_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/c/cb/Tw3_silver_plate.png/revision/latest?cb=20170216074401',
    [
      [
        'SILVER_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'THREAD',
    'https://vignette.wikia.nocookie.net/witcher/images/a/a4/Tw3_thread.png/revision/latest?cb=20170216062823',
    [
      [
        'COTTON',
        "",
        2
      ]
    ]
  ],
  [
    'ZERRIKANIAN_POWDER',
    'https://vignette.wikia.nocookie.net/witcher/images/7/77/Tw3_zerrikanian_powder.png/revision/latest?cb=20160410153144',
    [
      [
        'COAL',
        "",
        1
      ],
      [
        'SALTPETER',
        "",
        5
      ],
      [
        'SULFUR',
        "",
        1
      ],
    ]
  ],
];

const bwComponents = [
  [
    'GREEN_GOLD_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/a/ae/Tw3_green_gold_plate.png/revision/latest?cb=20170219080022',
    [
      [
        'GREEN_GOLD_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'GREEN_GOLD_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/2/22/Tw3_green_gold_ore.png/revision/latest?cb=20170219080021',
    [
      [
        'GOLD_NUGGET',
        "",
        4
      ],
      [
        'SILVER',
        "",
        5
      ],
      [
        'UNREFINED_COPPER_ORE',
        "",
        1
      ],
    ]
  ],
  [
    'GREEN_GOLD_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/2/22/Tw3_green_gold_ore.png/revision/latest?cb=20170219080021',
    [
      [
        'GREEN_GOLD',
        "",
        4
      ]
    ]
  ],
  [
    'GREEN_GOLD_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/1/12/Tw3_green_gold_ingot.png/revision/latest?cb=20170219080021',
    [
      [
        'GREEN_GOLD_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'ENRICHED_DIMERITIUM_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/5/51/Tw3_enriched_dimeritium_ingot.png/revision/latest?cb=20170219074308',
    [
      [
        'ENRICHED_DIMERITIUM_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'ENRICHED_DIMERITIUM_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/c/c2/Tw3_enriched_dimeritium_plate.png/revision/latest?cb=20170219074309',
    [
      [
        'ENRICHED_DIMERITIUM_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'ENRICHED_DIMERITIUM_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/5/5d/Tw3_enriched_dimeritium_ore.png/revision/latest?cb=20170219074308',
    [
      [
        'DIMERITIUM_ORE',
        "",
        1
      ],
      [
        'ORICHALCUM_ORE',
        "",
        1
      ],
      [
        'ACID_EXTRACT',
        "",
        1
      ],
    ]
  ],
  [
    'COPPER_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/2/27/Tw3_copper_ingot.png/revision/latest?cb=20170219074306',
    [
      [
        'COPPER_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'COPPER_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/f/f0/Tw3_copper_ore.png/revision/latest?cb=20170219074306',
    [
      [
        'UNREFINED_COPPER_ORE',
        "",
        5
      ]
    ]
  ],
  [
    'DARK_IRON_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/7/77/Tw3_dark_iron_plate.png/revision/latest?cb=20170216064640',
    [
      [
        'DARK_IRON_INGOT',
        "",
        1
      ]
    ]
  ],
  [
    'CUPRONICKEL_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/d/d0/Tw3_cupronickel_ore.png/revision/latest?cb=20170219074307',
    [
      [
        'UNREFINED_COPPER_ORE',
        "",
        3
      ],
      [
        'HUNK_OF_NICKEL',
        "",
        1
      ]
    ]
  ],
  [
    'COPPER_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/2/22/Tw3_copper_plate.png/revision/latest?cb=20170219074307',
    [
      [
        'COPPER_INGOT',
        "",
        2
      ]
    ]
  ],
  [
    'INFUSED_SLYZARD_HIDE',
    'https://vignette.wikia.nocookie.net/witcher/images/7/73/Tw3_infused_slyzard_hide.png/revision/latest?cb=20170219080023',
    [
      [
        'CURED_DRACONID_LEATHER',
        "",
        1
      ],
      [
        'INFUSED_CRYSTAL',
        "",
        1
      ]
    ]
  ],
  [
    'NICKEL_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/1/16/Tw3_nickel_ore.png/revision/latest?cb=20170219080151',
    [
      [
        'HUNK_OF_NICKEL',
        "",
        5
      ]
    ]
  ],
  [
    'ORICHALCUM_ORE',
    'https://vignette.wikia.nocookie.net/witcher/images/7/72/Tw3_orichalcum_ore.png/revision/latest?cb=20170219080152',
    [
      [
        'GREEN_GOLD',
        "",
        4
      ],
      [
        'UNREFINED_COPPER_ORE',
        "",
        3
      ],
      [
        'HUNK_OF_NICKEL',
        "",
        1
      ],
    ]
  ],
  [
    'ORICHALCUM_INGOT',
    'https://vignette.wikia.nocookie.net/witcher/images/3/38/Tw3_orichalcum_ingot.png/revision/latest?cb=20170219080151',
    [
      [
        'ORICHALCUM_ORE',
        "",
        2
      ]
    ]
  ],
  [
    'ORICHALCUM_PLATE',
    'https://vignette.wikia.nocookie.net/witcher/images/9/9b/Tw3_orichalcum_plate.png/revision/latest?cb=20170219080153',
    [
      [
        'ORICHALCUM_INGOT',
        "",
        2
      ]
    ]
  ],
];

const bwArmor = {
  "1": {
    name: "Grandmaster Feline Trousers",
    components:
      "1x Mastercrafted Feline Trousers\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Monster Tongue\n2x Monster Blood",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/f/fe/Tw3_armor_lynx_pants_5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531131552"
  },
  "2": {
    name: "Grandmaster Feline Boots",
    components:
      "1x Mastercrafted Feline Boots\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Monster Bone\n4x Monster Claw",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/0/01/Tw3_armor_lynx_boots_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531133658"
  },
  "3": {
    name: "Grandmaster Feline Armor",
    components:
      "1x Mastercrafted Feline Armor\n2x Infused Slyzard Hide\n2x Enriched Dimeritium Plate\n2x Monster Liver\n2x Monster Heart",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/5/5b/Tw3_grandmaster_feline_armor.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20170312174012"
  },
  "4": {
    name: "Grandmaster Feline Gauntlets",
    components:
      "1x Mastercrafted Feline Gauntlets\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Ingot\n2x Monster Bone\n1x Powdered Monster Tissue",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/d/de/Tw3_armor_lynx_gloves_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531133625"
  },
  "5": {
    name: "Grandmaster Wolven Armor",
    components:
      "1x Mastercrafted Wolven Armor\n2x Infused Slyzard Hide\n2x Enriched Dimeritium Plate\n1x Monster Heart\n1x Monster Stomach",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/2/2e/Tw3_armor_wolf_armor_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531124837"
  },
  "6": {
    name: "Grandmaster Wolven Boots",
    components:
      "1x Mastercrafted Wolven Boots\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n4x Monster Blood\n2x Monster Heart",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/c/c5/Tw3_armor_wolf_boots_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531124854"
  },
  "7": {
    name: "Grandmaster Wolven Gauntlets",
    components:
      "1x Mastercrafted Wolven Gauntlets\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Ingot\n2x Powdered Monster Tissue\n1x Monster Heart",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/4/49/Tw3_armor_wolf_gloves_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531124934"
  },
  "8": {
    name: "Grandmaster Wolven Trousers",
    components:
      "1x Mastercrafted Wolven Trousers\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Monster Blood\n2x Monster Heart",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/5/5e/Tw3_armor_bear_pants_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531141433"
  },
  "9": {
    name: "Manticore Armor",
    components:
      "1x Cured Draconid Leather\n2x Dimeritium Plate\n2x Monster Ear\n2x Monster Eye",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/f/f5/Tw3_armor_red_wolf_armor_1.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531131930"
  },
  "10": {
    name: "Manticore Boots",
    components:
      "1x Cured Draconid Leather\n1x Dimeritium Plate\n4x Monster Claw\n2x Monster Blood",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/7/71/Tw3_armor_red_wolf_boots_1.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531132231"
  },
  "11": {
    name: "Manticore Gauntlets",
    components:
      "1x Cured Draconid Leather\n1x Meteorite Silver Plate\n1x Monster Hair\n1x Monster Blood",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/9/9c/Tw3_armor_red_wolf_gloves_1.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531130841"
  },
  "12": {
    name: "Manticore Trousers",
    components:
      "1x Cured Draconid Leather\n1x Dimeritium Ingot\n1x Monster Claw\n2x Monster Blood",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/c/cf/Tw3_armor_red_wolf_pants_1.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531130950"
  },
  "13": {
    name: "Grandmaster Ursine Armor",
    components:
      "1x Mastercrafted Ursine Armor\n2x Infused Slyzard Hide\n2x Enriched Dimeritium Plate\n1x Monster Essence\n1x Monster Heart",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/0/0a/Tw3_armor_bear_armor_4.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531143958"
  },
  "14": {
    name: "Grandmaster Ursine Gauntlets",
    components:
      "1x Mastercrafted Ursine Gauntlets\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Ingot\n2x Monster Claw\n1x Powdered Monster Tissue",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/3/3f/Tw3_armor_bear_gloves_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531144130"
  },
  "15": {
    name: "Grandmaster Ursine Trousers",
    components:
      "1x Mastercrafted Ursine Trousers\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Monster Essence\n2x Monster Hair",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/5/5e/Tw3_armor_bear_pants_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531141433"
  },
  "16": {
    name: "Grandmaster Ursine Boots",
    components:
      "1x Mastercrafted Ursine Boots\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n3x Monster Saliva\n3x Monster Tooth",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/4/4c/Tw3_armor_bear_boots_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531144023"
  },
  "17": {
    name: "Grandmaster Griffin Armor",
    components:
      "1x Mastercrafted Griffin Armor\n2x Infused Slyzard Hide\n2x Enriched Dimeritium Plate\n2x Monster Heart\n1x Monster Essence",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/1/15/Tw3_griffin_armor_grandmaster.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20170322135938"
  },
  "18": {
    name: "Grandmaster Griffin Gauntlets",
    components:
      "1x Mastercrafted Griffin Gauntlets\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Ingot\n1x Monster Heart\n2x Monster Blood",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/1/1c/Tw3_armor_gryphon_gloves_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531143655"
  },
  "19": {
    name: "Grandmaster Griffin Trousers",
    components:
      "1x Mastercrafted Griffin Trousers\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Monster Blood\n2x Monster Brain",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/1/19/Tw3_armor_gryphon_pants_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531143714"
  },
  "20": {
    name: "Grandmaster Griffin Boots",
    components:
      "1x Mastercrafted Griffin Boots\n1x Infused Slyzard Hide\n1x Enriched Dimeritium Plate\n2x Powdered Monster Tissue\n4x Monster Claw",
    img:
      "https://vignette.wikia.nocookie.net/witcher/images/b/bb/Tw3_armor_gryphon_boots_lvl5.png/revision/latest/window-crop/width/40/x-offset/0/y-offset/4/window-width/64/window-height/48?cb=20160531143634"
  }
};

module.exports = {
  vanillaComponents,
  bwComponents,
  bwArmor
};